version: '3.7'

services:

  inter_process_comm:

    build:
      context: ..
      dockerfile: devops/Dockerfile.inter_process_comm
    container_name: inter_process_comm
    environment:
      # FLASK
      - FLASK_WINDOWS_PORT=5000
      - FLASK_DEFAULT_PORT=5000
      - FLASK_DEBUG_MODE=true
      - FLASK_HOST=0.0.0.0
      # LOGS
      - LOG_VERBOSITY=true
    volumes:
      - ../:/app
    ports:
      - 5000:5000
      