FROM python:3.8.5-slim-buster

# Directories :
COPY .                                          /app



WORKDIR                                         /app
RUN pip3 install -r                             /app/requirements/inter_process_comm.txt

#ENTRYPOINT [ "python3" ]
#CMD [ "main.py" ]

CMD python3 src/main.py

